/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  City, // @ts-ignore
  Customer,
} from "@prisma/client";

export class CityServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.CityCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.CityCountArgs>
  ): Promise<number> {
    return this.prisma.city.count(args);
  }

  async cities<T extends Prisma.CityFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CityFindManyArgs>
  ): Promise<City[]> {
    return this.prisma.city.findMany(args);
  }
  async city<T extends Prisma.CityFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CityFindUniqueArgs>
  ): Promise<City | null> {
    return this.prisma.city.findUnique(args);
  }
  async createCity<T extends Prisma.CityCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CityCreateArgs>
  ): Promise<City> {
    return this.prisma.city.create<T>(args);
  }
  async updateCity<T extends Prisma.CityUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CityUpdateArgs>
  ): Promise<City> {
    return this.prisma.city.update<T>(args);
  }
  async deleteCity<T extends Prisma.CityDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CityDeleteArgs>
  ): Promise<City> {
    return this.prisma.city.delete(args);
  }

  async getCustomer(parentId: string): Promise<Customer | null> {
    return this.prisma.city
      .findUnique({
        where: { id: parentId },
      })
      .customer();
  }
}
