/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Color, // @ts-ignore
  Customer,
} from "@prisma/client";

export class ColorServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ColorCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.ColorCountArgs>
  ): Promise<number> {
    return this.prisma.color.count(args);
  }

  async colors<T extends Prisma.ColorFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ColorFindManyArgs>
  ): Promise<Color[]> {
    return this.prisma.color.findMany(args);
  }
  async color<T extends Prisma.ColorFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ColorFindUniqueArgs>
  ): Promise<Color | null> {
    return this.prisma.color.findUnique(args);
  }
  async createColor<T extends Prisma.ColorCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ColorCreateArgs>
  ): Promise<Color> {
    return this.prisma.color.create<T>(args);
  }
  async updateColor<T extends Prisma.ColorUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ColorUpdateArgs>
  ): Promise<Color> {
    return this.prisma.color.update<T>(args);
  }
  async deleteColor<T extends Prisma.ColorDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ColorDeleteArgs>
  ): Promise<Color> {
    return this.prisma.color.delete(args);
  }

  async getCustomers(parentId: string): Promise<Customer | null> {
    return this.prisma.color
      .findUnique({
        where: { id: parentId },
      })
      .customers();
  }

  async getLikedColors(parentId: string): Promise<Customer | null> {
    return this.prisma.color
      .findUnique({
        where: { id: parentId },
      })
      .likedColors();
  }
}
